#!/usr/bin/env python3
"""Generate stub aFTR_PROFILE symbols so the registry check can link.

The real furniture profile table names ~700 profiles defined across the actor
tree. The registry check only cares about their addresses -- it is testing table
growth and the pointer swap, not furniture behaviour -- so linking the whole
actor tree would be a large cost for no signal.

Generated from include/f_furniture.h rather than hand-maintained, so a profile
added or renamed upstream cannot silently break the check.

Usage: gen_ftr_stubs.py <output.c>
"""
import re
import sys
import os

HEADER = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..",
                      "include", "f_furniture.h")


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)

    names = []
    with open(HEADER, encoding="utf-8", errors="replace") as source:
        for line in source:
            match = re.match(r"extern aFTR_PROFILE (\w+);", line.strip())
            if match:
                names.append(match.group(1))

    if not names:
        sys.exit("no aFTR_PROFILE declarations found in %s" % HEADER)

    with open(sys.argv[1], "w", encoding="utf-8") as out:
        out.write("/* Generated by tests/fuzz/gen_ftr_stubs.py -- do not edit.\n")
        out.write(" * Stand-in profiles so the registry check can link the real furniture\n")
        out.write(" * table without the actor tree. Only their addresses matter. */\n")
        out.write('#include "ac_furniture.h"\n\n')
        for name in names:
            out.write("aFTR_PROFILE %s;\n" % name)
        out.write("\n/* Referenced by pc_modloader.c's diagnostics. */\nint g_pc_verbose = 0;\n")

    print("generated %d stub profiles" % len(names))


if __name__ == "__main__":
    main()
